//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.ModeloEntityFramework.M
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO
    {
        public string ID_USUARIO { get; set; }
        public string NOMBRES { get; set; }
        public string APELLIDOS { get; set; }
        public string CONTRASENIA { get; set; }
        public Nullable<System.DateTime> FECHA_NACIMIENTO { get; set; }
        public string EMAIL { get; set; }
        public Nullable<int> CIUDAD_RESIDENCIA { get; set; }
        public byte SEXO { get; set; }
        public int OCUPACION { get; set; }
        public string TELEFONO_FIJO { get; set; }
        public string TELEFONO_MOVIL { get; set; }
        public bool FUMADOR { get; set; }
        public bool VEHICULO_PROPIO { get; set; }
        public byte[] FOTO { get; set; }
        public string MAS_INFO { get; set; }
    
        public virtual CIUDAD CIUDAD { get; set; }
        public virtual OCUPACION OCUPACION1 { get; set; }
    }
}
