//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CARPOOLINGEntities : DbContext
    {
        public CARPOOLINGEntities()
            : base("name=CARPOOLINGEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CORDENADA> CORDENADA { get; set; }
        public DbSet<TRAYECTO> TRAYECTO { get; set; }
        public DbSet<VIAJE> VIAJE { get; set; }
        public DbSet<USUARIO> USUARIO { get; set; }
    }
}
