//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO
    {
        public USUARIO()
        {
            this.VIAJE = new HashSet<VIAJE>();
        }
    
        public string ID_USUARIO { get; set; }
        public string NOMBRES { get; set; }
        public string APELLIDOS { get; set; }
        public string CONTRASENIA { get; set; }
        public Nullable<System.DateTime> FECHA_NACIMIENTO { get; set; }
        public string CIUDAD_RESIDENCIA { get; set; }
        public string EMAIL { get; set; }
        public Nullable<bool> SEXO { get; set; }
        public string OCUPACION { get; set; }
        public string TELEFONO_FIJO { get; set; }
        public string TELEFONO_MOVIL { get; set; }
        public string FUMADOR { get; set; }
        public string VEHICULO_PROPIO { get; set; }
        public byte[] FOTO { get; set; }
        public string MAS_INFO { get; set; }
    
        public virtual ICollection<VIAJE> VIAJE { get; set; }
    }
}
