//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIAJE
    {
        public VIAJE()
        {
            this.TRAYECTO = new HashSet<TRAYECTO>();
        }
    
        public long ID_VIAJE { get; set; }
        public System.DateTime FECHA_CREACION { get; set; }
        public Nullable<System.DateTime> FECHA_PARTIDA { get; set; }
        public string CREADOR { get; set; }
        public Nullable<byte> ROL { get; set; }
        public Nullable<byte> CUPOS { get; set; }
        public System.TimeSpan HORA_PARTIDA { get; set; }
    
        public virtual ICollection<TRAYECTO> TRAYECTO { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
