USE CARPOOL
;

--  Drop Foreign Key Constraints 
IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('FK_Calificacion_Evaluado') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE CALIFICACION DROP CONSTRAINT FK_Calificacion_Evaluado
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('FK_Calificacion_Evaluador') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE CALIFICACION DROP CONSTRAINT FK_Calificacion_Evaluador
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('FK_Calificacion_Viaje') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE CALIFICACION DROP CONSTRAINT FK_Calificacion_Viaje
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('FK_Ciudad_Departamento') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE CIUDAD DROP CONSTRAINT FK_Ciudad_Departamento
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('FK_Departamento_Pais') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE DEPARTAMENTO DROP CONSTRAINT FK_Departamento_Pais
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('FK_Parada_Trayecto') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE PARADA DROP CONSTRAINT FK_Parada_Trayecto
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('FK_Pregunta_Usuario') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE PREGUNTA DROP CONSTRAINT FK_Pregunta_Usuario
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('FK_Pregunta_Viaje') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE PREGUNTA DROP CONSTRAINT FK_Pregunta_Viaje
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('FK_Solicitud_Trayecto') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE SOLICITUD DROP CONSTRAINT FK_Solicitud_Trayecto
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('FK_Solicitud_Usuario') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE SOLICITUD DROP CONSTRAINT FK_Solicitud_Usuario
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('FK_Trayecto_Viaje') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE TRAYECTO DROP CONSTRAINT FK_Trayecto_Viaje
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('FK_Usuario_Ciudad') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE USUARIO DROP CONSTRAINT FK_Usuario_Ciudad
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('FK_Usuario_Ocupacion') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE USUARIO DROP CONSTRAINT FK_Usuario_Ocupacion
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('FK_Viaje_Usuario') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE VIAJE DROP CONSTRAINT FK_Viaje_Usuario
;


--  Drop Tables, Stored Procedures and Views 

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('CALIFICACION') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE CALIFICACION
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('CIUDAD') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE CIUDAD
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('DEPARTAMENTO') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE DEPARTAMENTO
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('OCUPACION') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE OCUPACION
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('PAIS') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE PAIS
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('PARADA') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE PARADA
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('PREGUNTA') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE PREGUNTA
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('SOLICITUD') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE SOLICITUD
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('TRAYECTO') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE TRAYECTO
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('USUARIO') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE USUARIO
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('VIAJE') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE VIAJE
;


--  Create Tables 
CREATE TABLE CALIFICACION ( 
	ID_CALIFICACION bigint identity(1,1)  NOT NULL,
	PUNTAJE decimal(3,2) NOT NULL,
	ID_VIAJE bigint NOT NULL,
	ID_EVALUADOR varchar(20) NOT NULL,
	ID_EVALUADO varchar(20) NOT NULL,
	FECHA_REALIZACION datetime NULL,
	COMENTARIO varchar(250) NULL
)
;

CREATE TABLE CIUDAD ( 
	ID_CIUDAD int NOT NULL,
	NOMBRE_CIUDAD varchar(30) NOT NULL,
	ID_DEPARTAMENTO int NULL
)
;

CREATE TABLE DEPARTAMENTO ( 
	ID_DEPARTAMENTO int NOT NULL,
	NOMBRE_DEPARTAMENTO varchar(30) NOT NULL,
	ID_PAIS int NOT NULL
)
;

CREATE TABLE OCUPACION ( 
	ID_OCUPACION int identity(1,1)  NOT NULL,
	NOMBRE_OCUPACION varchar(50) NOT NULL
)
;

CREATE TABLE PAIS ( 
	ID_PAIS int NOT NULL,
	NOMBRE_PAIS varchar(30) NOT NULL
)
;

CREATE TABLE PARADA ( 
	ID_PARADA bigint identity(1,1)  NOT NULL,
	ID_TRAYECTO bigint NOT NULL,
	LATITUD decimal(10,6) NOT NULL,
	LONGITUD decimal(10,6) NOT NULL,
	DIRECCION varchar(100) NOT NULL,
	NUMERO_PARADA int NOT NULL,
	TIPO_PARADA char(1) NOT NULL    --  Tipo parada: Origen o Destino 
)
;

CREATE TABLE PREGUNTA ( 
	ID_PREGUNTA bigint identity(1,1)  NOT NULL,
	ID_VIAJE bigint NOT NULL,
	ID_CREADOR_PREGUNTA varchar(20) NOT NULL,
	TEXTO_PREGUNTA varchar(500) NOT NULL,
	TEXTO_RESPUESTA varchar(500) NULL
)
;

CREATE TABLE SOLICITUD ( 
	ID_SOLICITUD bigint identity(1,1)  NOT NULL,
	ID_TRAYECTO bigint NOT NULL,
	ID_PASAJERO varchar(20) NOT NULL,
	CUPOS_SOLICITADOS int NOT NULL,
	COMENTARIO varchar(250) NULL,
	ESTADO int NOT NULL,    --  Estados: Pendiente por responder Aprobada  
)
;

CREATE TABLE TRAYECTO ( 
	ID_TRAYECTO bigint identity(1,1)  NOT NULL,
	ID_VIAJE bigint NOT NULL,
	CUPOS int NOT NULL,
	TRAYECTO_SIMPLE bit NOT NULL
)
;

CREATE TABLE USUARIO ( 
	ID_USUARIO varchar(20) NOT NULL,
	CONTRASENIA varchar(50) NOT NULL,
	NOMBRE varchar(30) NOT NULL,
	APELLIDO varchar(30) NOT NULL,
	EMAIL varchar(50) NOT NULL,
	FECHA_NACIMIENTO date NOT NULL,
	FECHA_ULTIMO_INGRESO datetime NOT NULL,
	GENERO char(1) NOT NULL,
	ID_CIUDAD_RESIDENCIA int NOT NULL,
	ID_OCUPACION int NOT NULL,
	TELEFONO_MOVIL varchar(15) NULL,
	TELEFONO_FIJO varchar(15) NULL,
	VEHICULO_PROPIO bit NOT NULL,
	FUMADOR bit NOT NULL,
	FOTO image NULL,
	INFORMACION_ADICIONAL varchar(800) NULL,
	REPUTACION decimal(4,2) NULL
)
;

CREATE TABLE VIAJE ( 
	ID_VIAJE bigint identity(1,1)  NOT NULL,
	FECHA_CREACION datetime NOT NULL,
	FECHA_HORA_PARTIDA datetime NOT NULL,
	ID_CONDUCTOR varchar(20) NULL,
	APORTE_ECONOMICO decimal(8,2) NOT NULL,
	INFORMACION_ADICIONAL varchar(800) NULL,
	ESTADO int NOT NULL,    --  Los estados posibles: Publicado, Cancelado Realizado... Documentarlos 
)
;


--  Create Primary Key Constraints 
ALTER TABLE CALIFICACION ADD CONSTRAINT PK_Calificacion 
	PRIMARY KEY CLUSTERED (ID_CALIFICACION)
;

ALTER TABLE CIUDAD ADD CONSTRAINT PK_Ciudad 
	PRIMARY KEY CLUSTERED (ID_CIUDAD)
;

ALTER TABLE DEPARTAMENTO ADD CONSTRAINT PK_Departamento 
	PRIMARY KEY CLUSTERED (ID_DEPARTAMENTO)
;

ALTER TABLE OCUPACION ADD CONSTRAINT PK_Ocupacion 
	PRIMARY KEY CLUSTERED (ID_OCUPACION)
;

ALTER TABLE PAIS ADD CONSTRAINT PK_Pais 
	PRIMARY KEY CLUSTERED (ID_PAIS)
;

ALTER TABLE PARADA ADD CONSTRAINT PK_Parada 
	PRIMARY KEY CLUSTERED (ID_PARADA)
;

ALTER TABLE PREGUNTA ADD CONSTRAINT PK_Pregunta 
	PRIMARY KEY CLUSTERED (ID_PREGUNTA)
;

ALTER TABLE SOLICITUD ADD CONSTRAINT PK_Solicitud 
	PRIMARY KEY CLUSTERED (ID_SOLICITUD)
;

ALTER TABLE TRAYECTO ADD CONSTRAINT PK_Trayecto 
	PRIMARY KEY CLUSTERED (ID_TRAYECTO)
;

ALTER TABLE USUARIO ADD CONSTRAINT PK_Usuario 
	PRIMARY KEY CLUSTERED (ID_USUARIO)
;

ALTER TABLE VIAJE ADD CONSTRAINT PK_Viaje 
	PRIMARY KEY CLUSTERED (ID_VIAJE)
;


--  Create Indexes 
ALTER TABLE USUARIO
	ADD CONSTRAINT UQ_Usuario_Email UNIQUE (EMAIL)
;


--  Create Foreign Key Constraints 
ALTER TABLE CALIFICACION ADD CONSTRAINT FK_Calificacion_Evaluado 
	FOREIGN KEY (ID_EVALUADO) REFERENCES USUARIO (ID_USUARIO)
;

ALTER TABLE CALIFICACION ADD CONSTRAINT FK_Calificacion_Evaluador 
	FOREIGN KEY (ID_EVALUADOR) REFERENCES USUARIO (ID_USUARIO)
;

ALTER TABLE CALIFICACION ADD CONSTRAINT FK_Calificacion_Viaje 
	FOREIGN KEY (ID_VIAJE) REFERENCES VIAJE (ID_VIAJE)
;

ALTER TABLE CIUDAD ADD CONSTRAINT FK_Ciudad_Departamento 
	FOREIGN KEY (ID_DEPARTAMENTO) REFERENCES DEPARTAMENTO (ID_DEPARTAMENTO)
;

ALTER TABLE DEPARTAMENTO ADD CONSTRAINT FK_Departamento_Pais 
	FOREIGN KEY (ID_PAIS) REFERENCES PAIS (ID_PAIS)
;

ALTER TABLE PARADA ADD CONSTRAINT FK_Parada_Trayecto 
	FOREIGN KEY (ID_TRAYECTO) REFERENCES TRAYECTO (ID_TRAYECTO)
;

ALTER TABLE PREGUNTA ADD CONSTRAINT FK_Pregunta_Usuario 
	FOREIGN KEY (ID_CREADOR_PREGUNTA) REFERENCES USUARIO (ID_USUARIO)
;

ALTER TABLE PREGUNTA ADD CONSTRAINT FK_Pregunta_Viaje 
	FOREIGN KEY (ID_VIAJE) REFERENCES VIAJE (ID_VIAJE)
;

ALTER TABLE SOLICITUD ADD CONSTRAINT FK_Solicitud_Trayecto 
	FOREIGN KEY (ID_TRAYECTO) REFERENCES TRAYECTO (ID_TRAYECTO)
;

ALTER TABLE SOLICITUD ADD CONSTRAINT FK_Solicitud_Usuario 
	FOREIGN KEY (ID_PASAJERO) REFERENCES USUARIO (ID_USUARIO)
;

ALTER TABLE TRAYECTO ADD CONSTRAINT FK_Trayecto_Viaje 
	FOREIGN KEY (ID_VIAJE) REFERENCES VIAJE (ID_VIAJE)
;

ALTER TABLE USUARIO ADD CONSTRAINT FK_Usuario_Ciudad 
	FOREIGN KEY (ID_CIUDAD_RESIDENCIA) REFERENCES CIUDAD (ID_CIUDAD)
;

ALTER TABLE USUARIO ADD CONSTRAINT FK_Usuario_Ocupacion 
	FOREIGN KEY (ID_OCUPACION) REFERENCES OCUPACION (ID_OCUPACION)
;

ALTER TABLE VIAJE ADD CONSTRAINT FK_Viaje_Usuario 
	FOREIGN KEY (ID_CONDUCTOR) REFERENCES USUARIO (ID_USUARIO)
;