//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.ModeloEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class CALIFICACION
    {
        public long IdCalificacion { get; set; }
        public decimal Puntaje { get; set; }
        public long IdViaje { get; set; }
        public string IdEvaluador { get; set; }
        public string IdEvaluado { get; set; }
        public Nullable<System.DateTime> FechaRealizacion { get; set; }
        public string Comentario { get; set; }
    
        public virtual USUARIO USUARIO_EVALUADO { get; set; }
        public virtual USUARIO USUARIO_EVALUADOR { get; set; }
        public virtual VIAJE VIAJE { get; set; }
    }
}
