//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.ModeloEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class SOLICITUD
    {
        public long ID_SOLICITUD { get; set; }
        public long ID_TRAYECTO { get; set; }
        public string ID_PASAJERO { get; set; }
        public int CUPOS_SOLICITADOS { get; set; }
        public string COMENTARIO { get; set; }
        public int ESTADO { get; set; }
    
        public virtual TRAYECTO TRAYECTO { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
