//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.ModeloEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRAYECTO
    {
        public TRAYECTO()
        {
            this.PARADA = new HashSet<PARADA>();
            this.SOLICITUD = new HashSet<SOLICITUD>();
        }
    
        public long IdTrayecto { get; set; }
        public long IdViaje { get; set; }
        public int Cupos { get; set; }
        public bool TrayectoSimple { get; set; }
    
        public virtual ICollection<PARADA> PARADA { get; set; }
        public virtual ICollection<SOLICITUD> SOLICITUD { get; set; }
        public virtual VIAJE VIAJE { get; set; }
    }
}
