//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.ModeloEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO
    {
        public USUARIO()
        {
            this.CALIFICACION_EVALUADO = new HashSet<CALIFICACION>();
            this.CALIFICACION_EVALUADOR = new HashSet<CALIFICACION>();
            this.PREGUNTA = new HashSet<PREGUNTA>();
            this.SOLICITUD = new HashSet<SOLICITUD>();
            this.VIAJE = new HashSet<VIAJE>();
        }
    
        public string IdUsuario { get; set; }
        public string Contrasenia { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public string Email { get; set; }
        public System.DateTime FechaNacimiento { get; set; }
        public System.DateTime FechaUltimoIngreso { get; set; }
        public string Genero { get; set; }
        public int IdCiudadResidencia { get; set; }
        public int IdOcupacion { get; set; }
        public string TelefonoMovil { get; set; }
        public string TelefonoFijo { get; set; }
        public bool VehiculoPropio { get; set; }
        public bool Fumador { get; set; }
        public byte[] Foto { get; set; }
        public string InformacionAdicional { get; set; }
        public Nullable<decimal> Reputacion { get; set; }
    
        public virtual ICollection<CALIFICACION> CALIFICACION_EVALUADO { get; set; }
        public virtual ICollection<CALIFICACION> CALIFICACION_EVALUADOR { get; set; }
        public virtual CIUDAD CIUDAD { get; set; }
        public virtual OCUPACION OCUPACION { get; set; }
        public virtual ICollection<PREGUNTA> PREGUNTA { get; set; }
        public virtual ICollection<SOLICITUD> SOLICITUD { get; set; }
        public virtual ICollection<VIAJE> VIAJE { get; set; }
    }
}
