//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.ModeloEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO
    {
        public USUARIO()
        {
            this.CALIFICACION_EVALUADO = new HashSet<CALIFICACION>();
            this.CALIFICACION_EVALUADOR = new HashSet<CALIFICACION>();
            this.PREGUNTA = new HashSet<PREGUNTA>();
            this.SOLICITUD = new HashSet<SOLICITUD>();
            this.VIAJE = new HashSet<VIAJE>();
        }
    
        public string ID_USUARIO { get; set; }
        public string CONTRASENIA { get; set; }
        public string NOMBRE { get; set; }
        public string APELLIDO { get; set; }
        public string EMAIL { get; set; }
        public System.DateTime FECHA_NACIMIENTO { get; set; }
        public System.DateTime FECHA_ULTIMO_INGRESO { get; set; }
        public string GENERO { get; set; }
        public int ID_CIUDAD_RESIDENCIA { get; set; }
        public int ID_OCUPACION { get; set; }
        public string TELEFONO_MOVIL { get; set; }
        public string TELEFONO_FIJO { get; set; }
        public bool VEHICULO_PROPIO { get; set; }
        public bool FUMADOR { get; set; }
        public byte[] FOTO { get; set; }
        public string INFORMACION_ADICIONAL { get; set; }
        public Nullable<decimal> REPUTACION { get; set; }
        public int ESTADO { get; set; }
    
        public virtual ICollection<CALIFICACION> CALIFICACION_EVALUADO { get; set; }
        public virtual ICollection<CALIFICACION> CALIFICACION_EVALUADOR { get; set; }
        public virtual CIUDAD CIUDAD { get; set; }
        public virtual OCUPACION OCUPACION { get; set; }
        public virtual ICollection<PREGUNTA> PREGUNTA { get; set; }
        public virtual ICollection<SOLICITUD> SOLICITUD { get; set; }
        public virtual ICollection<VIAJE> VIAJE { get; set; }
    }
}
