//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.ModeloEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIAJE
    {
        public VIAJE()
        {
            this.CALIFICACION = new HashSet<CALIFICACION>();
            this.PREGUNTA = new HashSet<PREGUNTA>();
            this.TRAYECTO = new HashSet<TRAYECTO>();
        }
    
        public long ID_VIAJE { get; set; }
        public System.DateTime FECHA_CREACION { get; set; }
        public System.DateTime FECHA_HORA_PARTIDA { get; set; }
        public string ID_CONDUCTOR { get; set; }
        public decimal APORTE_ECONOMICO { get; set; }
        public string INFORMACION_ADICIONAL { get; set; }
        public int ESTADO { get; set; }
    
        public virtual ICollection<CALIFICACION> CALIFICACION { get; set; }
        public virtual ICollection<PREGUNTA> PREGUNTA { get; set; }
        public virtual ICollection<TRAYECTO> TRAYECTO { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
