//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.ModeloEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class PARADA
    {
        public long IdParada { get; set; }
        public long IdTrayecto { get; set; }
        public decimal Latitud { get; set; }
        public decimal Lontitud { get; set; }
        public string Direccion { get; set; }
        public int NumeroParada { get; set; }
        public string TipoParada { get; set; }
    
        public virtual TRAYECTO TRAYECTO { get; set; }
    }
}
