//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.ModeloEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class PREGUNTA
    {
        public long IdPregunta { get; set; }
        public long IdViaje { get; set; }
        public string IdCreadorPregunta { get; set; }
        public string TextoPregunta { get; set; }
        public string TextoRespuesta { get; set; }
    
        public virtual USUARIO USUARIO { get; set; }
        public virtual VIAJE VIAJE { get; set; }
    }
}
