//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.ModeloEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class PREGUNTA
    {
        public long ID_PREGUNTA { get; set; }
        public long ID_VIAJE { get; set; }
        public string ID_CREADOR_PREGUNTA { get; set; }
        public string TEXTO_PREGUNTA { get; set; }
        public string TEXTO_RESPUESTA { get; set; }
    
        public virtual VIAJE VIAJE { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
