//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.ModeloEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class SOLICITUD
    {
        public long IdSolicitud { get; set; }
        public long IdTrayecto { get; set; }
        public string IdPasajero { get; set; }
        public int CuposSolicitados { get; set; }
        public string Comentario { get; set; }
        public int Estado { get; set; }
    
        public virtual TRAYECTO TRAYECTO { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
