//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.ModeloEntityFramework.P
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRAYECTO
    {
        public long ID_TRAYECTO { get; set; }
        public long ID_VIAJE { get; set; }
        public long COORDENADA_ORIGEN { get; set; }
        public long COORDENADA_DESTINO { get; set; }
        public byte CUPOS_DISPONIBLES { get; set; }
        public int INDEX_ORIGEN { get; set; }
        public int INDEX_DESTINO { get; set; }
        public string ES_SIMPLE { get; set; }
    
        public virtual CORDENADA CORDENADA { get; set; }
        public virtual CORDENADA CORDENADA1 { get; set; }
        public virtual VIAJE VIAJE { get; set; }
    }
}
